# visit:
# https://pre-commit.com/
# https://github.com/pre-commit/pre-commit-hooks/blob/master/.pre-commit-config.yaml
# https://blog.jerrycodes.com/pre-commit-is-awesome/

# overrides individual hooks that do not set language_version. (v1.14)
default_language_version:
  python: python3

# overrides individual hooks that do not set stages (v1.14)
default_stages: [commit, push]

# true to have pre-commit stop running hooks after first failure. (v1.1)
fail_fast: false

repos:

# alert on security issues with bandit
- repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  rev: v1.0.4
  hooks:
  - id: python-bandit-vulnerability-check
    args: []
    files: .py$

# format code using black
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3
# format "..code-block: python" in docs using black

- repo: https://github.com/asottile/blacken-docs
  rev: v1.2.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==19.3b0]
# hooks provided by the official team

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3  # replaces sha
  hooks:
  # check no big files are commited
  - id: check-added-large-files
    args: [--maxkb=1000]
  # check python syntax
  - id: check-ast
  # look for files that would conflict in case-insensitive filesystems
  - id: check-case-conflict
  # check json syntax
  - id: check-json
  # check yaml syntax
  - id: check-yaml
  # check for the existence of private ssh keys
  - id: detect-private-key
  # run flake8
  - id: flake8
  # sets a standard for formatting JSON file
  - id: pretty-format-json
    args: [--no-sort-keys, --autofix, --indent=4]
  #  sort requirements.txt file
  - id: requirements-txt-fixer
  # check and remove trailing whitespaces
  - id: trailing-whitespace
# format code by reordering import statements
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.3.5
  hooks:
  - id: reorder-python-imports
    language_version: python3
    args: ["--application-directories=.:shapr"]
