name: Generate and Publish Documentation
on:
  release:
    branches: [master]
    types: [published]

jobs:

  publish:
    name: Generate and Publish Documentation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Pandoc
        run: |
          sudo apt-get install pandoc
          pandoc -v

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install Dependencies
        run: |
          pip install -r requirements-docs.txt
          pip install -r requirements-true.txt

      - name: Generate Documentation
        run: make doc-html

      - name: Prepare Tag
        id: prepare_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_NAME="${GITHUB_REF##refs/tags/}"
          echo "::set-output name=tag_name::${TAG_NAME}"
          echo "::set-output name=deploy_tag_name::docs-${TAG_NAME}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          tag_name: ${{ steps.prepare_tag.outputs.deploy_tag_name }}
          tag_message: 'Deploy Docs ${{ steps.prepare_tag.outputs.tag_name }}'
